// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJkGH15kXuZwCu6ybX-fzm3mfO5SR7Ba0',
    appId: '1:285461224050:web:9d3d51cc082f93d4dc00eb',
    messagingSenderId: '285461224050',
    projectId: 'securityapp-c1318',
    authDomain: 'securityapp-c1318.firebaseapp.com',
    storageBucket: 'securityapp-c1318.firebasestorage.app',
    measurementId: 'G-S56QXE5NDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnO7vxTKNnnykW2yMcpSvWgFegg5uneY',
    appId: '1:285461224050:android:f390ca11ec4eb924dc00eb',
    messagingSenderId: '285461224050',
    projectId: 'securityapp-c1318',
    storageBucket: 'securityapp-c1318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5eyjsMg54R1F3zSaBzNnHMtq4wFQzMo',
    appId: '1:285461224050:ios:4d1233c5af4956bddc00eb',
    messagingSenderId: '285461224050',
    projectId: 'securityapp-c1318',
    storageBucket: 'securityapp-c1318.firebasestorage.app',
    iosBundleId: 'com.example.securityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy5eyjsMg54R1F3zSaBzNnHMtq4wFQzMo',
    appId: '1:285461224050:ios:4d1233c5af4956bddc00eb',
    messagingSenderId: '285461224050',
    projectId: 'securityapp-c1318',
    storageBucket: 'securityapp-c1318.firebasestorage.app',
    iosBundleId: 'com.example.securityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJkGH15kXuZwCu6ybX-fzm3mfO5SR7Ba0',
    appId: '1:285461224050:web:b2f3ff59a1a96451dc00eb',
    messagingSenderId: '285461224050',
    projectId: 'securityapp-c1318',
    authDomain: 'securityapp-c1318.firebaseapp.com',
    storageBucket: 'securityapp-c1318.firebasestorage.app',
    measurementId: 'G-M43PNFJL62',
  );
}
